# Generated by Django 5.2.9 on 2025-12-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Адрес', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.TextField(blank=True, help_text='Номер телефона пользователя', max_length=12, null=True),
        ),
    ]
