import "./reset.css";
import "./base.css";
import "./ui.css"
import "./header.css";
import "./hero.css"
import "./product.css"
import "./bestSellers.css"
import "./bigProduct.css"
import "./review.css"
import "./productReviewsList.css"
import "./morePhotos.css"
import "./lastReviews.css"
import "./footer.css"
import "./authForm.css"