# Generated by Django 5.2.9 on 2025-12-13 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartItem', '0001_initial'),
        ('product', '0002_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
    ]
