# Generated by Django 5.2.9 on 2025-12-03 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название товара', max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField(help_text='Введите описание товара', max_length=1000)),
                ('rating', models.IntegerField(help_text='Рейтинг должен быть от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
    ]
