# Generated by Django 5.2.9 on 2025-12-06 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0, help_text='Рейтинг должен быть от 1 до 5', validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
