# Generated by Django 5.2.9 on 2025-12-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
